version: "3"
services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
  postgresql:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=shortit
      - POSTGRES_USER=shortit
      - POSTGRES_PASSWORD=shortit
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
